name: Bug report
description: Report a bug
title: "[Bug] "
labels: ['bug', 'triage']
assignees: 
 - Jab125
 - 3e2j
body:
- type: input
  attributes:
    label: Minecraft Username
    description: What is your Minecraft Username?
    placeholder: Ex. Steve
  validations:
    required: true
- type: dropdown
  attributes:
    label: Version
    description: What version of Goblin Traders are you using?
    multiple: false
    options:
      - 1.0.0
      - 1.0.1
      - 1.0.2
      - 1.0.3
      - 1.0.4
      - 1.0.5
      - 1.1.0
      - 1.1.1
      - 1.2.0
      - 1.3.0
      - 1.4.0
      - 1.5
      - 1.5.1
      - latest commit
  validations:
    required: true
- type: dropdown
  attributes:
    label: Minecraft Version
    multiple: false
    options:
      - 1.16.*
      - 1.17.*
      - 1.18.*
      - 1.18.2
- type: textarea
  attributes:
    label: What did you expect?
    description: "What was meant to happen?"
  validations:
    required: true
- type: textarea
  attributes:
    label: What did you get?
    description: "What actually happened?"
  validations:
    required: true
- type: markdown
  attributes:
    value: "Thanks for helping make this mod better"
